version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - .env
    ports:
      - "5433:5432"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.1
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

networks:
  esnet:
    driver: bridge
